# Generated by Django 3.1.3 on 2020-11-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urllist',
            old_name='url',
            new_name='longUrl',
        ),
    ]
