# Generated by Django 3.1.3 on 2020-11-16 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urllist',
            old_name='url',
            new_name='longUrl',
        ),
        migrations.CreateModel(
            name='AnalyticsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessedOn', models.DateTimeField(auto_now=True)),
                ('ip', models.TextField(max_length=40)),
                ('userAgent', models.TextField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlShortenerApp.urllist', verbose_name='test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
