# Generated by Django 3.1.3 on 2020-11-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslist',
            name='browserType',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analyticslist',
            name='browserVersion',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analyticslist',
            name='deviceType',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analyticslist',
            name='osType',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analyticslist',
            name='osVersion',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
