# Generated by Django 3.1.3 on 2020-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0003_remove_analyticslist_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslist',
            name='shortUrl',
            field=models.TextField(default='null', max_length=200),
        ),
    ]
