# Generated by Django 3.1.3 on 2020-11-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0003_auto_20201117_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticslist',
            options={'ordering': ['-id']},
        ),
    ]
