# Generated by Django 3.1.3 on 2020-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0004_auto_20201117_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='expiryDatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
