# Generated by Django 3.1.3 on 2020-12-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortenerApp', '0005_urllist_expirydatetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urllist',
            options={'ordering': ['-id']},
        ),
    ]
